version: "2"

services:

  web:
    image: silintl/ssp-base:latest
    ports:
      - "80:80"
    volumes:
      - ./:/silauth
      - ./auth.json:/root/.composer/auth.json
      - ./development/ldap/dev-ldap.conf:/etc/ldap/ldap.conf
      - ./development/run-dev.sh:/data/run-dev.sh
      - ./src:/data/src
    env_file:
      - ./common.env
      - ./local.env
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: silauth
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth
    links:
      - db
      - ldap
    command: ["/data/run-dev.sh"]

  tests:
    image: silintl/ssp-base:latest
    volumes_from:
      - web
    volumes:
      - ./composer.json:/data/composer.json
      - ./composer.lock:/data/composer.lock
      - ./features:/data/features
      - ./vendor:/data/vendor
    env_file:
      - ./common.env
      - ./local.env
    environment:
      MYSQL_HOST: testdb
      MYSQL_DATABASE: test
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth
    links:
      - testdb
      - ldap
    working_dir: /data

  db:
    image: silintl/mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: silauth
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth

  testdb:
    image: silintl/mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: test
      MYSQL_USER: silauth
      MYSQL_PASSWORD: silauth

  dbadmin:
    image: silintl/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db

  ldap:
    build:
      context: ./development/ldap
      dockerfile: Dockerfile
    ports:
      - "389"
    env_file:
      - ./common.env
    working_dir: /data
    environment:
      DEBUG_LEVEL: 320

  ldapload:
    build:
      context: ./development/ldap
      dockerfile: Dockerfile
    working_dir: /data
    env_file:
      - ./common.env
    environment:
      DEBUG_LEVEL: 320
    links:
      - ldap
    volumes:
      - ./development/ldap/fakepeople.ldif:/root/fakepeople.ldif
      - ./development/ldap/fakerep.ldif:/root/fakerep.ldif
    command: bash -c "sleep 10 && /data/load_ldap.sh"

  ldapadmin:
    image: silintl/phpldapadmin:latest
    links:
      - ldap
    ports:
      - "8000:80"
    env_file:
      - ./common.env
    environment:
      DISPLAY_NAME: Password Store
      HOST: ldap
      PORT: 389
      BASE: dc=acme,dc=org

